### ISSUE TITLE
Question: How do you get the current screensize?

### ISSUE THREAD

**Issue by aiwha-dev** [Genex/ng2-mmbreakpoints#1]
I notice I only  get the screensize on change of the viewport.

Is there a way to get the current screensize onload?

**Comment by mattirwin** [comment]
Correct, this is updated on screen change by design.  

I think what you are talking about is possible, but I'm not clear on specifics.

First, what do you mean exactly by "get the screensize", can you give me an example of what you are referencing exactly?

**Comment by aiwha-dev** [comment]
We'll basically if you want to know screensize changes, and you want to know the change. 
You'd probably need to know the initial state (so the initial 'ev' on component load). Atleast I do.

We're using it to decide what template should be loaded.

Basically i solved it like this now. For us this is enough, preferrably you'd get the full contents of 'ev' on load though.

```
this.isMobile = (window.matchMedia(this.matchmediaService.breakpoints['xs']) || {matches: false}).matches || false;
this.matchmediaService.matchmediaChanges.subscribe((ev) => {
	this.isMobile = ev.mediaCustom === 'xs';
});
```

**Comment by mattirwin** [comment]
I see.

The service uses window.matchMedia internally. There is also another publicly available object that exposes the matchMedia function run by the service _matchmediaCollection_.  This means you shouldn't have to call matchMedia again, you could do something like this: 

`this.isMobile = this.matchmediaService.matchmediaCollection.xs.matches || false;`
